version: "3.9"
services:
  mobilecap:
    image: mobilecap
    volumes:
      - data:/data
    env_file:
      - ../.env
    environment:
      - DOCKERCOMPOSE=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  openpose:
    image: openpose
    volumes:
      - data:/openpose/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  mmpose:
    image: mmpose
    volumes:
      - data:/mmpose/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  data: {}
